services:
  - type: web
    name: repo-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm ci
    startCommand: node index.js
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: MONGODB_URI
        value: mongodb+srv://repo:Moamenla%40123@cluster0.585ib8d.mongodb.net/repo?appName=Cluster0
      - key: PORT
        value: 5000
    disk:
      name: uploads
      mountPath: /opt/render/project/src/backend/uploads
      sizeGB: 2
